'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

def isFib(fib1, fib2):
    fib = fib1 + fib2
    
    return [fib, fib2]


num = isFib(1,2)
sumnum = 2
i = 3
fib = num[0]
while fib < 4000000:
    i += 1
    num = isFib(num[1], num[0])
    fib = num[0]
    if (fib % 2) == 0:
        sumnum += fib
        print(fib,sumnum)

print(sumnum)
